var myString;
var myNum;
var myBool;
var myVar;
var myVoid = undefined;
var myNull = null;
var myUndefined = undefined;
// let strArr: string[];
// let numArr: number[];
// let boolArr: boolean[];
var strArr;
var numArr;
var boolArr;
var strNumTuple;
myString = '1';
myNum = 22;
myBool = true;
myVar = 'ueor';
strArr = ['one', 'two', 'Bulgaria'];
numArr = [1, 2, 46];
boolArr = [true, true, false];
strNumTuple = ['Hello', 4];
console.log(myString);
